In [ ]:
import time
import numpy as np

inicio = time.time()  # Marca o início do tempo de execução do código

def add_matrix(A, B):
    # Adiciona duas matrizes A e B e retorna a matriz resultante
    return [[A[i][j] + B[i][j] for j in range(len(A))] for i in range(len(A))]

def sub_matrix(A, B):
    # Subtrai a matriz B da matriz A e retorna a matriz resultante
    return [[A[i][j] - B[i][j] for j in range(len(A))] for i in range(len(A))]

def strassen(A, B):
    n = len(A)
    if n == 1:
        # Caso base: multiplicação direta se a matriz é 1x1
        return [[A[0][0] * B[0][0]]]

    mid = n // 2  # Calcula o meio para dividir a matriz
    # Divide a matriz A em quatro submatrizes
    A11 = [row[:mid] for row in A[:mid]]
    A12 = [row[mid:] for row in A[:mid]]
    A21 = [row[:mid] for row in A[mid:]]
    A22 = [row[mid:] for row in A[mid:]]

    # Divide a matriz B em quatro submatrizes
    B11 = [row[:mid] for row in B[:mid]]
    B12 = [row[mid:] for row in B[:mid]]
    B21 = [row[:mid] for row in B[mid:]]
    B22 = [row[mid:] for row in B[mid:]]

    # Calcula os produtos intermediários M1 a M7 usando o algoritmo de Strassen
    M1 = strassen(add_matrix(A11, A22), add_matrix(B11, B22))
    M2 = strassen(add_matrix(A21, A22), B11)
    M3 = strassen(A11, sub_matrix(B12, B22))
    M4 = strassen(A22, sub_matrix(B21, B11))
    M5 = strassen(add_matrix(A11, A12), B22)
    M6 = strassen(sub_matrix(A21, A11), add_matrix(B11, B12))
    M7 = strassen(sub_matrix(A12, A22), add_matrix(B21, B22))

    # Combina os produtos intermediários para formar a matriz resultante C
    C11 = add_matrix(sub_matrix(add_matrix(M1, M4), M5), M7)
    C12 = add_matrix(M3, M5)
    C21 = add_matrix(M2, M4)
    C22 = add_matrix(sub_matrix(add_matrix(M1, M3), M2), M6)

    # Cria uma matriz n x n de zeros
    C = np.zeros((n, n), dtype=int)

    # Preenche a matriz C com as submatrizes calculadas
    for i in range(mid):
        for j in range(mid):
            C[i][j] = C11[i][j]
            C[i][j + mid] = C12[i][j]
            C[i + mid][j] = C21[i][j]
            C[i + mid][j + mid] = C22[i][j]

    return C

def criar_matriz_par():
    while True:
        try:
            n = int(input("Digite o tamanho da matriz (deve ser um número par): "))
            if n % 2 != 0:
                # Garante que o número inserido seja par
                print("Por favor, digite um número par.")
            else:
                break
        except ValueError:
            # Trata o erro caso o usuário insira um valor inválido
            print("Por favor, digite um número válido.")

    # Cria duas matrizes n x n com números aleatórios entre 0 e 20
    matrizA = np.random.randint(0, 21, size=(n, n))
    matrizB = np.random.randint(0, 21, size=(n, n))

    fim = time.time()  # Marca o fim do tempo de execução do código
    tempo_execucao = fim - inicio  # Calcula o tempo total de execução

    # Imprime as matrizes geradas
    print(f"\nMatriz A {n}x{n} com números aleatórios:\n")
    print(matrizA)
    print(f"\nMatriz B {n}x{n} com números aleatórios:\n")
    print(matrizB)

    # Converte as matrizes para listas e calcula a multiplicação usando Strassen
    matrizC = strassen(matrizA.tolist(), matrizB.tolist())
    print(f"\nResultado da multiplicação das matrizes A e B usando o algoritmo de Strassen:\n")
    print(np.array(matrizC))  # Converte o resultado de volta para um array numpy

    # Imprime o tempo total de execução
    print(f"Tempo de execução: {tempo_execucao} segundos")

if __name__ == "__main__":
    criar_matriz_par()  # Chama a função principal quando o script é executado diretamente


Digite o tamanho da matriz (deve ser um número par): 2

Matriz A 2x2 com números aleatórios:

[[ 1  2]
 [19 19]]

Matriz B 2x2 com números aleatórios:

[[16 10]
 [17 11]]

Resultado da multiplicação das matrizes A e B usando o algoritmo de Strassen:

[[ 50  32]
 [627 399]]
Tempo de execução: 2.2213447093963623 segundos
